object Test {
  try 2/0 catch {
    case e: Exception =>
  }
}